apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/chaos: "true"
  labels:
    app: sock-shop
    name: payment
  name: payment
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sock-shop
      name: payment
  template:
    metadata:
      labels:
        app: sock-shop
        name: payment
    spec:
      containers:
      - image: weaveworksdemos/payment:0.4.3
        imagePullPolicy: IfNotPresent
        name: payment
        ports:
        - containerPort: 80
          protocol: TCP
<<<<<<< HEAD
        securityContext:
=======
>>>>>>> cc710042767e103f82610ca187a09bd064e897e1
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
<<<<<<< HEAD
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
=======

>>>>>>> cc710042767e103f82610ca187a09bd064e897e1
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: payment

